### ISSUE TITLE
Refactor logic isaAverage to isaPoints

### ISSUE THREAD

**Issue by everson-ever** [Sintrop/SAT-core-contracts#13]

**Comment by everson-ever** [comment]
# IsaAverage refacotor

### Now the isaAverage must be isaPoints. Each Isa has your own point:
- TOTALLY_SUSTAINABLE = 1 point
- PARTIAL_SUSTAINABLE = 1 point
- NEUTRO = 1 point
- PARTIAL_NOT_SUSTAINABLE = 0 point
- TOTALLY_NOT_SUSTAINABLE = 0 point

 **OBS**  : All points are examples that can change in any time


### Example:
To a inspection that receive the follow isas:
isas = [[1, 0], [2, 0], [3, 3]]  **OBS** zero possition is the category and the first position is the isa index
The final points of the inspection must be:
1 + 1 + 0 = 3 points

The logica of the isa is that a index refer to a isa:
index 0 = TOTALLY_SUSTAINABLE 
index 1 = PARTIAL_SUSTAINABLE 
index 2 = NEUTRO 
index 3 = PARTIAL_NOT_SUSTAINABLE 
index 4 = TOTALLY_NOT_SUSTAINABLE

**Comment by everson-ever** [comment]
@rav-andre Só valida pra mim por favor

**Comment by rav-andre** [comment]
Não entendi esse sistema de pontuação. Não íamos usar a outra escala de pontuação?
Parcial e total não podem ter a mesma pontuação.

Se não me engano era essa escala que a gente tinha conversado:

TOTALLY_SUSTAINABLE = 10000 point
PARTIAL_SUSTAINABLE = 1000 point
NEUTRO = 100 point
PARTIAL_NOT_SUSTAINABLE = 10 point
TOTALLY_NOT_SUSTAINABLE = 1 point

**Comment by rav-andre** [comment]
@everson-ever Ainda não definitivo, pensei em uma mudança nos valores das pontuações.
A diferença apenas de 0 para 1 acaba sendo pequena e dificulta um pouco a mensuração.

Nova pontuação:

TOTALLY_SUSTAINABLE = 10 points
PARTIALLY_SUSTAINABLE = 5 points
NEUTRO = 1 point
PARTIALLY_NOT_SUSTAINABLE = 0 point
TOTALLY_NOT_SUSTAINABLE = 0 point

E aí mantemos a lógica de somar os isa points obtidos com os votos em cada categoria. 

Para permitir que o produtor participe da pool de produtores e ganhe tokens, podemos colocar como a nota de corte sendo 5 isapoints multiplicado pela quantidade de categorias.

Ou seja, em uma cenário onde o ISA possui 3 categorias, a nota de corte seria 15 isa points. Em um cenário que possui 10 categorias, a nota de corte seria de 50 isa points. Nesse caso, a nota de corte também poderia ser calculada como o total de isapoints possíveis, caso um produtor seja totalmente sustentável em tudo dividido por dois.

Se ficou alguma dúvida mande aqui por favor.
