### ISSUE TITLE
Fix Ocaco server port

### ISSUE THREAD

**Issue by everson-ever** [Sintrop/SAT-core-contracts#14]
# Fix server port

- Remove 5000 port listen from server.js to stop second server execution at same time

**Comment by everson-ever** [comment]
@BrennoGomez Não esquece de checar esse tbm! Analisa o server pra ver como eletá rodando

**Comment by rav-andre** [comment]
Fala pessoal. Reforçando aqui que essa parte dos projetos nesse repositório é exclusiva do desenvolvimento da Sintrop. Tudo sobre o Ocaco devemos fazer a mesma coisa no respositório do Ocaco da Afiliart beleza?
